### ISSUE TITLE
Add example for sending HTTP requests with Guzzle

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/t3docs-examples#108]
Use in: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Http/Index.html#basic-usage

Maybe a command or a middleware.

**Comment by DavidBruchmann** [comment]
Looks obsaolete to me, see:
https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/7

**Comment by brotkrueml** [comment]
> Looks obsolete to me, see: [TYPO3-Documentation/Changelog-To-Doc#7](https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/7)

The RST is about Extbase, the example is about making a request with Guzzle.
