### ISSUE TITLE
Example for own LinkHandler (GitHub) produces 503 error in Link Browser

### ISSUE THREAD

**Issue by codingnik** [TYPO3-Documentation/t3docs-examples#164]
When selecting "GitHub Issue" in Link Browser a 503 is happening.

503 Oops, an error occurred!
Tried resolving a template file for controller action "Standard->linkBrowser" in format ".html", but none of the paths contained the expected template file (Standard/LinkBrowser.html). The following paths were checked: /var/www/typotest/typotest/public/typo3/sysext/recordlist/Resources/Private/Templates/LinkBrowser/

TYPO3 11.5.17
examples 11.1.1

**Comment by DavidBruchmann** [comment]
I suspect that this part is wrong as it repeats `typotest`, can you confirm?
```
/var/www/typotest/typotest
```

**Comment by codingnik** [comment]
I'm closing the ticket as I cannot recall the context. Most probably it has been a wrong path in my code.
