### ISSUE TITLE
throws a error on installation :: 12.4

### ISSUE THREAD

**Issue by joka123** [TYPO3-Documentation/t3docs-examples#194]
(1/1) #1303237468 RuntimeException
Given select field item list was not found.

at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTcaSelectItem('sys_reaction', 'reaction_type', array('label' => 'Example reaction type', 'value' => 'example-reaction-type', 'icon' => 'tx_examples-dummy'))
in /html/typo3/typo3conf/ext/examples/Configuration/TCA/Overrides/sys_reaction.php line 18

**Comment by brotkrueml** [comment]
Thanks for the report. I can reproduce a similar behaviour: 

    Implementation class for reaction type "example-reaction-type" is missing.

**Comment by brotkrueml** [comment]
@joka123 Currently, I cannot reproduce your problem. Can you give more information, especially when the error occurs? On a `composer require` or on a cache flush or when navigation to the reactions module?

**Comment by joka123** [comment]
hm, today i tried again the installation and everything works fine. it's a dev installation and i changed many things in the last days. may be i have forgotten to clear autodump or there was a conflict with one of my extensions. so sorry vor wasting your time.
