### ISSUE TITLE
Examples break right-click menu in composer environment and slows down typo3 [V10.0.2] [ddev]

### ISSUE THREAD

**Issue by sayore** [TYPO3-Documentation/t3docs-examples#21]
In my testing Intance of ddev(copied from the typo3 site to make the instance), typo3 sems to slow down by a lot, also very randomly and the right-click context menu in the page tree will not open.

Using V10.4.12 of typo and V10.0.2 of the extension

**Comment by linawolf** [comment]
Closed as we do not work on v10 anymore
