### ISSUE TITLE
12.4 branch + PHP 8.2: dynamically declared porperties in ModuleController::initializeAction() needs to be declared

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/t3docs-examples#221]
- `$this->pageUid`
- `$this->exampleConfig`

needs to be declared statically to work also with supported PHP version 8.2 in TYPO3 12.4 branch.

Should I simply add them, or is this something we don't want to fix in the example extension for a TYPO3 core version is not `dev-main`.

**Comment by brotkrueml** [comment]
@josefglatz Thanks for the report. I provided a fix which will be backported to the 12.4 branch.
