### ISSUE TITLE
typo3 extension:setup -e examples fails in TYPO3 12.latest.stable

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/t3docs-examples#254]
```
Uncaught TYPO3 Exception Call to a member function set() on null
thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Authentication/AbstractUserAuthentication.php
in line 112
```

- TYPO3 12.latest.stable
- Extension Tag 12.0.4

**Comment by brotkrueml** [comment]
@josefglatz I can't reproduce it with the current 12.4 and main branches of EXT:examples.

    ddev typo3 extension:setup -e examples

    [OK] Extension(s) "examples" successfully set up.        

Can you check, if the error occurs with the recent version?

I will also publish a new version 12.0.5 shortly.

**Comment by linawolf** [comment]
With 13.0 this is also working.
