### ISSUE TITLE
Problem with custom LinkHandler

### ISSUE THREAD

**Issue by wtfred** [TYPO3-Documentation/t3docs-examples#41]
Hello there,
Not sure if this the place to report my problem, but here i go :)

I'm on TYPO3 10.4.17
I'm tried to implement a custom LinkHandler, by following https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/LinkBrowser/Linkhandler/CustomLinkHandlers.html and looking in https://github.com/TYPO3-Documentation/t3docs-examples/commit/5214a8b681108011a21de4297a59d7797defb145
I think i followed by the letter the implementation of the github link, but:
In `GitHubLinkHandler.php`, in function `canHandleLink`, the array `$linkParts` i'm retrieving is not the same as you seems to get.
Instead of having something like (like the one i get if i debug in EXT:recordlist `TelephoneLinkHandler.php`)
```
[
  'url' => [
    'github' => 321
  ]
  'type' => 'github'
]

```
I'm having
```
[
  'url' => [
    'url' => 'github:321',
    'value' => 321
  ]
  'type' => 'github'
]
```
Did i miss something? Is that normal or is there an error in the documentation?
Do i need to correct `if (isset($linkParts['url']['github'])) {` by something like `if(strpos($linkParts['url']['url'], 'github') === 0){`

Thanks!

**Comment by linawolf** [comment]
Try following https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/LinkBrowser/Linkhandler/ while you are using TYPO3 10.4. If this doesnt help try asking your question in the typo3 slack
