### ISSUE TITLE
XClass for create new record causes error 

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-examples#60]

**Comment by linawolf** [comment]
Once this is fixed, the screenshot "XclassNewElementWizard" in TYPO3 explained has to be commented in and fixed

**Comment by PhilippKuhlmay** [comment]
This is an error message for this issue.
`Fatal error: Declaration of T3docs\Examples\Xclass\NewRecordController::renderNewRecordControls(Psr\Http\Message\ServerRequestInterface $request): void must be compatible with TYPO3\CMS\Backend\Controller\NewRecordController::renderNewRecordControls(): void in /var/www/html/public/typo3conf/ext/examples/Classes/Xclass/NewRecordController.php on line 35`

**Comment by DavidBruchmann** [comment]
The issue is the last line:
```
    protected function renderNewRecordControls(): void
    {
        parent::renderNewRecordControls();
        $label = $GLOBALS['LANG']->sL('LLL:EXT:examples/Resources/Private/Language/locallang.xlf:help');
        $text = $GLOBALS['LANG']->sL('LLL:EXT:examples/Resources/Private/Language/locallang.xlf:make_choice');
        $str = '<div><h2 class="uppercase" >' . htmlspecialchars($label) . '</h2>' . $text . '</div>';

        $this->content .= $str;
    }
```
because "$this->content" does not exist.
The called parent method assigns values directly to the view and "$this->content" is not defined.

**Comment by DavidBruchmann** [comment]
My approach would be to assign the new string to "additionalContent" in the xClass:
```php
    protected function renderNewRecordControls(): void
    {
        parent::renderNewRecordControls();
        $label = $GLOBALS['LANG']->sL('LLL:EXT:examples/Resources/Private/Language/locallang.xlf:help');
        $text = $GLOBALS['LANG']->sL('LLL:EXT:examples/Resources/Private/Language/locallang.xlf:make_choice');
        $str = '<div><h2 class="uppercase" >' . htmlspecialchars($label) . '</h2>' . $text . '</div>';

        $this->view->assign('additionalContent', $str);
    }
}
```
 and add this then to a copy of the template `typo3/sysext/backend/Resources/Private/Templates/NewRecord/NewRecord.html`:
```xml
    <div class="row mb-4">
        <div class="col-12">
            <strong>Additional Content</strong>
            <div class="list-group mt-2">
                {additionalContent -> f:format.html()}
            </div>
        </div>
    </div>
```
I never found out though how to change the path-reference of the template to the extension examples.

**Comment by DavidBruchmann** [comment]
As [NewRecordController](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Controller/NewRecordController.php#L351) is using the [final class ModuleTemplate](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Template/ModuleTemplate.php#L47) it's quite difficult to change the behavior without copying much code. The line `parent::renderNewRecordControls();` in the xClass is prohibiting that adjustments can be made, hence the whole method had to be copied and the adjustments made at the end.
BTW: the method [`ModuleTemplate::initLegacyView()`](https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Template/ModuleTemplate.php#L339) to assign template-paths is protected and can't be accessed, the paths are hardcoded.

**Comment by linawolf** [comment]
As the sole purpose of this code is to show how an XClass is working, could we maybe just find another example for an XClass? XClassing is prone to change

**Comment by DavidBruchmann** [comment]
ok, I'll think about it where to add one.

**Comment by DavidBruchmann** [comment]
for the moment I tend to remove this xclass first.
