### ISSUE TITLE
Section on Flash messages refers to "examples" extension but with missing file

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3docs-examples#7]
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlashMessages/Index.html#flash-messages-in-extbase

> The messages are then displayed by Fluid with the relevant ViewHelper as shown in this excerpt of EXT:examples/Resources/Private/Layouts/Module.html:

File Resources/Private/Layouts/Module.html does not exist in this extension. Might be a good idea to either update the documentation or add this layout.

**Comment by linawolf** [comment]
This seems to be resolved?
