### ISSUE TITLE
Recommend to add CI: lint, static analyzer (phpstan) and possibly tests

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3docs-examples#80]
As is customary in core and recommended extensions. 

I saw an initialized and unused variable, see #78. This is not a real problem but static analyzer would detect these kind of things and possibly other problems as well.

Also, this extension supports several core versions (in various branches) and it is a heck of a job to keep this maintained and working. So, some tests and static analyzer might help there as well (though keeping that updated as well is an additional challenge so probably best to start with minimal).

Besides propagating best practices :smile:

**Comment by brotkrueml** [comment]
Linting and CGL is already there: https://github.com/TYPO3-Documentation/t3docs-examples/blob/main/.github/workflows/tests.yml

For best practises the tea extension maybe better.

**Comment by brotkrueml** [comment]
Rector is now also available, adding rules step by step.

**Comment by sypets** [comment]
@brotkrueml Should we close this now if it is (mostly) done?

**Comment by brotkrueml** [comment]
Yup, I am also not sure if phpstan makes sense, at least for the upper levels. Maybe I will try it later.
