### ISSUE TITLE
Clicking buttons in Flash Message BE module does not work

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/t3docs-examples#83]
In the examples BE module "Flash queue", there are 2 buttons which can be clicked. A flash message should get displayed when this happens.

![image](https://user-images.githubusercontent.com/13206455/178481107-92ec4db7-6f35-47fa-8a30-ff20c7bd71a0.png)

* nothing happens if the buttons are clicked
* It looks like the file Application.js is not included and is not called.

Apparently, the JavaScript on "click" event handler in Application.js should get called, which will then execute the Ajax call tx_examples_count which will use ModuleController::countAction.

Alternatively, instead of using JavaScript, the countAction could be called directly and submit the FlashMessage as described in https://review.typo3.org/c/Packages/TYPO3.CMS/+/74582/7/typo3/sysext/core/Documentation/Changelog/12.0/Feature-97595-ProvideDefaultQueueForNotifications.rst

## Versions

* latest "main" of exmples
* latest "main" of TYPO3 core (coredev installation)

## Related:

* https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/108

**Comment by linawolf** [comment]
I can confirm, this works in 11.5 but not in main
